default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: tasktracker_dev


test:
  <<: *default
  database: tasktracker_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  port: 5432

staging:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  port: 5432


  